#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    bootstrap_before = 'myspacevim#before'
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    # colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
# auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'core#banner'
enable = false

[[layers]]
name = "colorscheme"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#ruby'
enabled_linters = ['rubocop']

[[custom_plugins]]
repo = 'vim-ruby/vim-ruby'
merged = false

# [[layers]]
# name = "lang#javascript"

[[layers]]
name = "fzf"

[[layers]]
name = 'lang#c'

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#dockerfile"

# [[layers]]
# name = "lang#typescript"

[[layers]]
name = "tmux"

[[layers]]
name = "VersionControl"

[[layers]]
name = "gtags"
gtagslabel = "ctags"
